spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/seubanco
    username: seuusuario
    password: suasenha
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
